### ISSUE TITLE
Text area on pop-up too big

### ISSUE THREAD

**Issue by akhyarrh** [dmison/Serum#1]
![2015-07-06_08 34](https://cloud.githubusercontent.com/assets/10618799/8514168/617544f2-23ba-11e5-8e4c-0892f26cf8b6.png)

...and I can't scroll and I use netbook (1024x600). Thank you

**Comment by dmison** [comment]
sorry for not replying initially.  

I was thinking of dynamically re-sizing the height based on browser view-port.

**Comment by akhyarrh** [comment]
Remove `height` declaration maybe okay

**Comment by dmison** [comment]
sorry for letting this anguish for so long - I've just done a major rewrite which incorporates dynamically adjusting the height of the editor.  This has been push to the Chrome store.

See https://github.com/dmison/Serum/commit/817911070936ca6179477e059a807317d62f748f
