### ISSUE TITLE
you shouldn't loose your edits if the popup closes

### ISSUE THREAD

**Issue by dmison** [dmison/Serum#3]
It's really annoying to either close it by mistake, or want to go back to the page to check something or copy something else and have to close the popup and thus loose work.

Perhaps draft posts should be cached in local storage & restored if the popup is opened on the same URL

probably would need to provide some indication (change colour of icon?) if you are on a page with a saved draft

possibly also a UI for managing saved drafts

**Comment by phillipadsmith** [comment]
Yes, indeed, @dmison: I was trying to write a quick technical post today and lost my edits several times as I tabbed to my terminal to check something. Super-frustrating! :-)

**Comment by dmison** [comment]
Dropped the "pop-up" UI.  Now creates a new "panel" style window instead.  

https://github.com/dmison/Serum/commit/266e24d84be99c211495c7d35684949694ca5f00
